### ISSUE TITLE
[Error] 깃헙 PR 불가... ㅠㅠ

### ISSUE THREAD

**Issue by Minhyeong-S** [tastekim/WeAllLie-BE#15]
### 한 일

- schema/index.js(몽고디비 접속), schema/users 생성
- mongo.js 삭제
- app.js에 패스포트 사용시 필요한 미들웨어 추가

### 에러 내용

PR 진행하려고 했으나 진행이 안됩니다...
제가 어제 실수로 연결되어 있던 제 로컬 깃 상태를 초기화 하는 바람에 연결이 끊어져서 그런 것 같습니다.

### 조치 사항

다시 클론 받고 
(로컬)
마스터 브랜치에서 user/login 브랜치 생성하고 
깃헙의 user/login 브랜치를 내 로컬의 user/login 에 pull 하고
충돌 해결 후 rebase 진행했고
그 후 다시 user/login 으로 pull 
그리고 나서 다시 PR 진행해봤는데 똑같네요.. ㅠㅠ
뭔가 제가 잘못한 부분이 있으면 알려주세요 ㅠㅠ

### 환경 설정

```cmd
OS: Mac OS Monterey 12.6
Node:  v16.17.1
npm : v8.15.0 
```

**Comment by tastekim** [comment]
user/login의 브랜치가 master 랑 머지되기 전이였어서 뭔가 user/login 브랜치 상태가 꼬인거같은데,,,
아예 원격에 있는 user/login 브랜치를 없애고 깃 클론 후에 로컬에서 user/login 브랜치를 새로 만들고 그 브랜치로 원격에 새로 생성해보는건 어떨까요,,,?!?! 물론 user/login 내용은 다른 곳에 킾해두시고,.,,,

**Comment by Minhyeong-S** [comment]
해보겠습니당

**Comment by Minhyeong-S** [comment]
해결!!
