### ISSUE TITLE
[Doc] WebSocket 과 socket.io의 차이

### ISSUE THREAD

**Issue by kimhsno1** [tastekim/WeAllLie-BE#29]
## 주제
 - 웹소켓과 소켓아이오는 어떤 차이가 있을까?

## 웹소켓
  - 웹소켓은 양방향 소통을 위한 프로토콜입니다.
   여기서 프로토콜은 '서로 다른 컴퓨터끼리 소통하기 위한 약속' 이라고 하네요

## socket.io
 - socket.io 는 양방향 통신을 하기 위해 웹소켓 기술을 활용하는 라이브러리 입니다.
   자바스크립트와 jQuery의 관계와 비슷하다고 볼 수 있습니다.

## 차이점

# 웹소켓
 - HTML5 웹 표준 기술이기 때문에 오래된 버전의 웹 브라우저는 웹소켓을 지원하지 않습니다.
 - 매우 빠르게 작동하며 통신할 때 적은 데이터를 이용함
 - 이벤트를 단순히 듣고 보내는 것만 가능함

# socket.io
 - 표준 기술은 아니고 라이브러리
 - 소켓 연결 실패 시 fallback을 통해 다른 방식으로 알아서 해당 클라이언트와 연결을 시도함
 - 방 개념을 이용해 일부 클라이언트에게만 데이터를 전송하는 브로드캐스팅이 가능함
 - 같은 기능을 구현하더라도 약간 느리지만 많은 편의성을 제공하며 Java, C++, Python 등 여러 언어들의 라이브러리 또한 지원

## 사용하는 기준?
- 통상적으로 사용자(서버에 연결된 소켓들)을 세밀하게 관리해야하는 서비스에는 
   socket.io에 있는 브로드캐스팅을 사용하는게 더 효율적이라고 합니다.
   반면 사용자보다는 데이터전송이 주로 이루어지는 경우 예를들어 주식 시장을 보는 경우에는 
   적은 데이터를 사용해 빠르게 볼 수 있는 웹소켓이 더 바람직 하다고 합니다.

**Comment by tastekim** [comment]
namespace의 느낌이 잘 나온 것 같아서 가져와 봅니다 !
### socket 서버 구조화 그림
![스크린샷 2022-11-13 오전 5 19 42](https://user-images.githubusercontent.com/112174727/201493018-38983c11-bb18-4ecc-bac4-c525bfc023bf.png)

### socket.io에서 제공하는 미들웨어 기능
![스크린샷 2022-11-13 오전 5 20 03](https://user-images.githubusercontent.com/112174727/201493060-f14fa081-badf-458f-a739-9d68079ea582.png)

**Comment by Minhyeong-S** [comment]
오 소켓에서 미들웨어 이렇게 쓰는거군용!!

**Comment by tastekim** [comment]
@Minhyeong-S 마침 소켓에 미들웨어를 어떻게 사용해야되는지 보고계셨었네요 ㅋㅋㅋㅋㅋ👍🏻
