### ISSUE TITLE
[Error] socket.io 작성할때 소켓을 나눠서 작성 할 수 없다는 사실~

### ISSUE THREAD

**Issue by kimhsno1** [tastekim/WeAllLie-BE#30]
### 한 일

작성 과정에서 시작할때
`const room = io.of('/room/lobby/roomIndex');`
로 room의 경로를 설정하고 소켓안에서 일어나는 io 영역과 게임 방안에서 일어나는 room 영역을 나누어서 작성을 했습니다.
게임방 내에서 작동하기 때문에 io.on 이 아닌 room.on, 로비에서는 lobby.on 을 이용해 작성을 했는데

### 에러 내용

```cmd
room.io('connection', async(socket) => {
     ^

TypeError: room.io is not a function
```
room.io 부분에 에러가 발생 하더군요 ㅠ
### 조치 사항

io.on, room.on, lobby.on 으로 나누는게 아니라 
큰 io,on 안에 모두 넣고 실행 하였을 때는 서버가 정상적으로 작동 되었습니다.
방별로 나누어서 작성하는건 안되나봅니다..

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by tastekim** [comment]
혹시 `const room = io.of('/room/lobby/roomIndex');` 코드가 있는 파일에서 io 모듈 require 해올 때 어떻게 작성됬는지 볼 수 있나요 ?!

**Comment by kimhsno1** [comment]
처음 가져올때 `const io = require('../socket');` 로 가져오고 그 뒤 수정은 없었습니다
```
const io = require('../socket');
const lobby = io.of('/room/lobby');
const room = io.of('/room/lobby/roomIndex');
```

**Comment by tastekim** [comment]
처음 io로 가져와서 'connection'이벤트를 받아 socket server와 연결을 먼저 한 후에 그 다음에 io.of의 내용이 와보는건 어떨까요,,,?!

```javascript
const room = require('../socket');
    
room.on('connection', (socket) => {
    const lobby = io.of('/room/lobby');
    const room = io.of('/room/lobby/roomIndex');
}
``` 

이런 식으로요,,!

**Comment by kimhsno1** [comment]
결과부터 말씀 드리자면 서버는 정상적으로 켜집니다. 
그런데 연석님 말씀에서 약간 힌트를 얻었는데요
로비와 룸을 io.on 안에서 선언을 했지만 room과 lobby가 io영역안이 아닌 밖에 작성이 되있었기 때문에
선언은 되었지만 읽히지 않았었는데
io.on 안에다가 room.on 과 lobby.on 을 옮겨 넣었더니 서버는 정상적으로 켜졌습니다

**Comment by tastekim** [comment]
곧 PR이 올라오겟군여⭐️

**Comment by kimhsno1** [comment]
이제 새로운 문제가 생겼는데 콘솔에 서버가 켜진걸로 나오지만 Postman에 연결을 시도 했을때는 
`TypeError: room.io is not a function` 가 다시 나옵니다

**Comment by kimhsno1** [comment]
```TypeError: room.io is not a function
    at Namespace.<anonymous> (C:\Users\ktjkp\WeAreLie\src\rooms\room-socket.js:51:6)
```
라고 뜨는걸 보니까 room의 네임스페이스가 제대로 선언이 안되었나봅니다.

**Comment by kimhsno1** [comment]
room.on 인데 room.io 라고 적어서 실행이 안된거였습니다 ㅠ
진짜 바보같네요...

**Comment by tastekim** [comment]
아 server.js에 저 파일도 require 해주어야 합니다 !

```javascript
// server.js

const http = require('./app');
require('dotenv').config();
require('./socket');
require('./game/game-socket') // <- 여기처럼요 ! 이건 제로컬의 경우입니다 !
const mongodb = require('./schemas/index');

mongodb();

http.listen(process.env.PORT, () => {
  console.log(`connect on http://127.0.0.1:${process.env.PORT}`);
});

```

**Comment by tastekim** [comment]
> room.on 인데 room.io 라고 적어서 실행이 안된거였습니다 ㅠ 진짜 바보같네요...

아하?ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by kimhsno1** [comment]
네 require도 잘되었고 이제 포스트맨으로 이벤트만 확인하면 됩니당 ㅋㅋ

**Comment by kimhsno1** [comment]
결국 처음 썼던대로 전체범위에서 선언하고 따로 작성해도 됩니다 !!!!!!!!!!!!!!!!!
#해결 내용 : room.io -> room.on
