### ISSUE TITLE
우리 지금 ES6 문법 사용하는게 아니라서 babel.config.json 빼고 그냥 사용하고 싶은데 어떠신가요? 

### ISSUE THREAD

**Issue by Minhyeong-S** [tastekim/WeAllLie-BE#4]
괜히 root 폴더에 의미없는 json 파일이 두 개나 있는 것 같아서요!

**Comment by tastekim** [comment]
전 찬성입니다 ! 그럼 babel 설치한 부분들도 다 제거해도 괜찮은거죠?

**Comment by Minhyeong-S** [comment]
babel 설치 붑분은 다 제거해도 되고, nodemon.json 제거하고 그냥 원래처럼 package.json에서 스크립트로 server.js 동작시켰는데 잘 켜집니다!!

**Comment by tastekim** [comment]
그러면 제가 메인 브랜치에서 수정해서 PR 작성해보겠습니다! 지금 보니까 제가 repository도 그렇고 package.json 에도 그렇고 이름을 'we all lie' 가 아니라 'we are lie'라고 해놨더라구요,,,,,^^

라이브러리 제거 및 파일 제거 랑 package.json 수정해서 PR 작성해보겠습니다 !

**Comment by kimhsno1** [comment]
좋습니다!

**Comment by Minhyeong-S** [comment]
적용한 상태 push했습니다!

**Comment by tastekim** [comment]
@kimhsno1 @Minhyeong-S @yunjin5450 
생각해보니까 저희가 쓰는 javascript가 ES6 이후 문법들 아닌가요,,,?
let, const 부터가 ES6부터 나온 문법이고 화살표 함수 등 저희가 쓰는 것들이 전부 ES6이지 않나? 라는 생각이 들었습니다,,!

물론 저희 서버 코드들은 브라우저에서 실행되는 코드들이 아니니 babel을 사용할 이유가 없지않나라고 생각은 드는데 알아보다가 명쾌한 해답을 아직 못얻어서 기술멘토링노트에 추가로 작성은 해놨습니다.

**Comment by Minhyeong-S** [comment]
전체문법이 아니라 모듈 사용에 대해서 commomJS 인지 ES6 인지 그부분에 대한 거라고 알고 있어요. 
일단 저도 더 찾아보겠습니다.

**Comment by Minhyeong-S** [comment]
babel 사용하기로 결정 ~ _~
