### ISSUE TITLE
[Error] 방을 생성한것과 생성한 사람이 방으로 자동으로 들어가지는것은 다르다는걸 알고 계신가요?

### ISSUE THREAD

**Issue by kimhsno1** [tastekim/WeAllLie-BE#43]
### 한 일

 - 방 출입을 작성하는 과정에서 입장하면 현재입장인원이 올라가고 퇴장하면 내려가는 기술은 눈으로 확인 했습니다.
 - 하지만 방을 생성한 당사자는 leaveRoom이 작동을 안하더라고요
 - 제 생각에는 방을 생성한다는게 생성과 동시에 방으로 입장되는것이 아닌 말 그대로 방만 만들어진것 같습니다.

 - 퇴장하는 과정에서 마지막남아있는 사람이 leaveRoom을 실행하면 1 -> 0 이 아닌 1 -> -1 이 되어버립니다.

### 조치 할 예정

 -  방을 생성하고 입장까지 연결시켜주기
 - 퇴장할때 currentCount를 1 -> 0 으로 만들기

### 환경 설정

```cmd
OS: Windows 10
Node:  v16.15.1 (@unchaptered), v16.13.1(@axisotherwise)
npm : v8.11.0 (@unchaptered), v8.2.2 (@axisotherwise)
```

**Comment by tastekim** [comment]
#35 방을 생성할때도 바로 join으로 입장시켜주는데 왜 방을 생성한 사람이랑 입장한 사람이랑 leaveRoom이 다르게 적용되는걸까요 ,,,
뭔가 또 저희가 모르는 게 있을수도 있겟네요,,ㅎ,,,
아마 currentCount는 0이 false와 같아서 -1로 표현되는게 아닐까요....?!
