### ISSUE TITLE
[Doc] Redis 사용법

### ISSUE THREAD

**Issue by tastekim** [tastekim/WeAllLie-BE#49]
# 🟥Redis
Redis는 Memcached와 비슷한 캐시 시스템으로서 동일한 기능을 제공하면서 영속성, 다양한 데이터 구조와 같은 부가적인 기능을 지원하고 있습니다. 레디스는 모든 데이터를 메모리에 저장하고 조회합니다. 즉, 인메모리 데이터베이스 입니다. 이 말만 들으면 Redis에 모든 데이터를 메모리에 저장하는 빠른 DB가 다라고 생각할지도 모릅니다. 하지만 빠른 성능은 레디스의 특징 중 일부분 입니다. 다른 인메모리 디비들과의 가장 큰 차이점은 레디스의 다양한 자료구조 입니다.

## ❓사용이유
- 각 게임에 대해 투표 결과 집계나 각 게임 준비 상태 등 DB에 저장할 필요는 없지만 I/O이 빈번한 간단한 액션들에 대해 가볍게 저장해 둘 DB를 찾다가 memcached랑 redis 가 후보였는데 memcached보다 redis가 cloud서비스로도 제공이 되고 초기 세팅하기에 더 빨라서 선택하게 됬습니다.간단한 데이터 타입들과 key, value 형식으로 저장할 수 있는 메모리를 사용하는 DB라서 위에서 언급한 저런 데이터들의 I/O을 다루기에는 redis가 적합하다고 생각했습니다. 
- redis를 선택할 때 local과 cloud 두가지 옵션이 있었는데 협업하면서 사용하기에는 아무래도 local보단 cloud가 더 효율적일 것 같다는 생각이 들었습니다.

## 🔍사용방법
```javascript
// redis를 사용하는 파일에서 모듈을 임포트해줍니다.(저희 프로젝트 기준)
const redisCli = require('../redis.js')

// 데이터 저장(key, value)
await redisCli.set('test', 'abc')

// 데이터 조회(key)
await redisCli.get('test')

// key 존재여부 확인 -> 1 or 0
await redisCli.exists('test')

// 특정 key 값의 value 값에 대한 증가 또는 감소 값을 가져올때 incr / decr 명령을 사용한다.
await redisCli.set('a', 1)
await redisCli.incr('a') // 2
await redisCli.decr('a') // 1

// 특정 key 삭제
await redisCli.rm('test')

// 특정 key에 유효시간 설정 -> second 단위
await redisCli.expire('a', 60) // 60초 후 삭제

// 그 외에 다양한 명령어들이 많습니다. 당장 많이 쓰일 것 같은 명령어들만 정리해봤습니다.
```

**Comment by Minhyeong-S** [comment]
와 정리 감사합니다!!

**Comment by tastekim** [comment]
## 에러 내용
redis 연결 후 간단한 get, set 테스트 후에 공지했는데 lpush, rpush, 그 외에 여러 메소드에서 자꾸 없는 함수라고 뜨고 아무리 뒤져봐도 저건데 자꾸 저희 플젝에서는 먹지를 않아서 서칭중에 npm에 `ioredis` 라는 nodejs 전용 redis 클라이언트라는 라이브러리가 있네요,,,

## 해결 방안
로컬에서 테스트해보니 업데이트도 최근이고 기존 redis cloud에서는 DB에 뭐가 있는지 알수가 없었는데 이건 GUI툴도 제공하고 redis 모든 기능을 담고있어서 이걸로 꺾어보려고 서칭중입니다^_____^

👇참고 문서
[npm ioredis](https://www.npmjs.com/package//ioredis)
[ioredis git](https://github.com/luin/medis)

@kimhsno1 @Minhyeong-S @yunjin5450

**Comment by tastekim** [comment]
# 🟥ioredis
redis의 모든 명령어를 지원합니다. Node.js 전용이라 호환도 좋고 사용방법도 기존의 redis보다 훨씬 간단합니다.
redis의 기본 기능들을 node의 내장 모듈을 활용하여 간단하게 구현할 수 있는 기능들이 제공됩니다.

## 💾ioredis GUI
![스크린샷 2022-11-16 오전 7 40 37](https://user-images.githubusercontent.com/112174727/202042744-d18c6aa5-240a-4129-ab3f-a1678ba34e24.png)

## 🔍사용 방법
### redis와 동일합니다 !
