### ISSUE TITLE
[Doc] Prettier, ESLint, Babel

### ISSUE THREAD

**Issue by tastekim** [tastekim/WeAllLie-BE#61]
# 🤝Prettier / ESLint / Babel
### 1. Prettier
- 코드 포멧터(Code Formatter)란 개발자가 작성한 코드를 정해진 코딩 스타일을 따르도록 변환해주는 도구를 말합니다. Prettier는 이러한 코드 포멧터 중에서도 최근에 가장 인기를 많이 얻어 거의 표준이 되고 가고 있는 자바스크립트 라이브러리 입니다.
### 2. ESLint
- ESLint는 JavaScript, JSX의 정적 분석 도구로 오픈 소스 프로젝트입니다. 코드를 분석해 문법적인 오류나 안티 패턴을 찾아주고 일관된 코드 스타일로 작성하도록 도와줍니다. JSLint, JSHint와 같이 다른 JavaScript 정적 분석 도구들도 있지만, ESLint가 커스터마이징이 쉽고 확장성이 뛰어나 많이 쓰이고 있는 추세입니다. ESLint는 스타일 가이드를 좀 더 편리하게 적용하기 위해 사용하기도 하는데, 외부에 공개되어 많은 개발자가 사용 중인 Airbnb, Google 이 그 대표적인 예입니다.
### 3. Babel
- Babel을 이용하면 ES6 이상의 최신 문법으로 작성한 자바스크립트 코드를 ES5 이하의 예전 문법으로 작성한 것 처럼 소스 코드 내의 문법의 형태를 변경할 수 있습니다. 이렇게 Babel을 통해 문법 형태가 바뀐 소스 코드는 최신 문법을 지원하는 실행 환경 뿐만 아니라 아직 최신 문법들이 적용되지 않은 실행 환경에서도 문제없이 작동하게 됩니다.

### 1. prettier
- 깔끔한 코드와 협업을 위해서 일관성 있는 코드 스타일을 제공해주기 때문에.
### 2. eslint
- 다양한 방식으로 구현할 수 있는 코드 방식을 일관성 있게 구현할 수 있도록 해주기 때문에.
### 3. babel
- Babel을 이용하면 ES6 이상의 최신 문법으로 작성한 자바스크립트 코드를 ES5 이하의 예전 문법으로 작성한 것 처럼 소스 코드 내의 문법의 형태를 변경해주어 다양한 실행환경에서 작동할 수 있게 해주기 때문에.

## 🔍사용방법
각 필요한 라이브러리들은 전부 설치해놓았습니다.  

**⭐️PR 전에 ESLint로 발생하는 문법 에러에 대해 수정 후 Prettier 설정으로 정리한 후에 PR 을 작성해주시면
불필요한 conflict는 피할 수 있을 것 같습니다.⭐️**

@kimhsno1 @Minhyeong-S @yunjin5450

**Comment by tastekim** [comment]
window나 vscode 등 각 해당되는 처음 세팅이 있을 수 있습니다 !
한번 확인해보시면 좋을 것 같습니다 !

**Comment by Minhyeong-S** [comment]
확인했습니다!

**Comment by yunjin5450** [comment]
확인했습니다!
